import type { Metadata } from "next";
import "./globals.css";
import { 
  merriweather_sans_serif, 
  poppins_sans, 
  quicksand_sans } from "./utils/fonts";
import { MainHeader } from "./components/layout/header/main";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>


const RootLayout = ({ children }: RootLayoutProps) =>{

  return (
    <html
      className="scroll-smooth" 
      lang="en">
      <body className={`${ quicksand_sans } ${ poppins_sans } ${ merriweather_sans_serif } font-quicksand`}>
        {children}
      </body>
    </html>
  );
}


export default RootLayout